SUBDIR+=overview
SUBDIR+=week-1
SUBDIR+=week-2
SUBDIR+=week-3
SUBDIR+=week-4
SUBDIR+=week-5
SUBDIR+=week-6
SUBDIR+=week-7
SUBDIR+=week-8
SUBDIR+=week-9
SUBDIR+=week-labweek

MAKEFILES_INCLUDE=../makefiles
include ${MAKEFILES_INCLUDE}/subdir.mk
