MODULE ?= Lab Week (June)
MODULE_RE ?= Lab Week
PULL_COURSE ?= tilkry25
PULL_MODULE_RE ?= $(MODULE_RE)

include ../module.mk

.PHONY: pull-pages
pull-pages:
	@echo "No pages (Page items) in ${MODULE}."

.PHONY: pull-assignments
pull-assignments:
	@echo "No assignments in ${MODULE}."
