.PHONY: all
all: hashsign.pdf

FILES=		hashsign.tex hashsign.bib

hashsign.pdf: ${FILES}


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
INCLUDE_BIBSP=../bibsp
include ${INCLUDE_BIBSP}/bibsp.mk
