.PHONY: all
all: hashsign.pdf

FILES=		hashsign.tex hashsign.bib

hashsign.pdf: ${FILES}


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
INCLUDE_LIBBIB=../libbib
include ${INCLUDE_LIBBIB}/libbib.mk
